# Generated by Django 6.0.3 on 2026-03-10 14:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_remove_activity_end_date_remove_activity_end_time_and_more'),
        ('organiser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('volunteer', 'activity')},
        ),
    ]
