# Generated by Django 4.2.29 on 2026-03-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser', '0002_alter_application_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
